### ISSUE TITLE
unfortunately the game crashes  MC 1.19.3

### ISSUE THREAD

**Issue by MCRobin1962** [aftersans53228/Minecraft-AFRoads-Mod#2]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'aft_fabroads'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:465)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more
Caused by: java.lang.IllegalStateException: Duplicate item group: aft_fabroads:normal_road_blocks
	at net.fabricmc.fabric.impl.itemgroup.ItemGroupHelper.appendItemGroup(ItemGroupHelper.java:42)
	at net.fabricmc.fabric.impl.itemgroup.FabricItemGroupBuilderImpl.method_47324(FabricItemGroupBuilderImpl.java:41)
	at net.aftersans53228.aft_fabroads.FabroadsMod.<clinit>(FabroadsMod.java:415)

**Comment by XieXiLin3** [comment]
Sorry
