### ISSUE TITLE
Loader 顯示找不到任何的 fabric api

### ISSUE THREAD

**Issue by SODAISpod** [aftersans53228/Minecraft-AFRoads-Mod#3]
您好
安裝模組後，loader會回傳錯誤，並顯示：
[21:27:49] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.7
[21:27:49] [main/WARN]: Mod resolution failed
[21:27:49] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE aft_fabroads 1.0.0 {depends fabric-api @ [*]}, ROOT_FORCELOAD_SINGLE aft_fabroads 1.0.0]
[21:27:49] [main/INFO]: Reason: [HARD_DEP aft_fabroads 1.0.0 {depends fabric-api @ [*]}]
[21:27:49] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, fabric-keybindings-v0, sodium, fabric-renderer-registries-v1, fabric-textures-v0, modmenu, fabric-models-v0, fabric-rendering-v0, fabric-screen-api-v1, fabric-key-binding-api-v1, fabric-rendering-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1]
[21:27:49] [main/INFO]: Fix: add [add:fabric-api 1 ([(-∞,∞)])], remove [], replace []
[21:27:49] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric-api, any version.
Unmet dependency listing:
	 - Mod 'Aftersans53228's fabric roads' (aft_fabroads) 1.0.0 requires any version of fabric-api, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.7.jar:?]

實際上已經有在 mods 內放置 fabric-api-0.58.0+1.19 檔案了。
在 server 跟 client 都有測試過了，後來嘗試修改 fabric.mod.json 內的檔案，把 "depends": 底下的 "fabric-api": "*", 那行刪掉就通過檢查了，這似乎不是跟 mod 本身有關的問題，而是 loader 檢查上有問題？ 

版本為：aftersans53228-fabric-road+1.0.1+1.19+Release.jar
是從modrinth下載的
minecraft 的版本為 1.19 loader 0.14.7

**Comment by XieXiLin3** [comment]
经查，旧版本的 Fabric API 的 ID 为 **fabric** ，
已联系修复，如有问题请继续提出。

**Comment by aftersans53228** [comment]
已修复，原因是fabricapi在minecraft1.19.2之后将modid"fabric"改为了"fabric-api",而这里强制需求"fabric_api"
modrinth上已更新新的mod文件。
由于其本身需要兼容1.19,1.19.1,1.19.2，因此暂时删除fabric api的fabric.mod.json强制需求。（但实际上依旧需要fabric api）
